version: "3.9"
services:
  app:
    build:
      context: ./productApp
      dockerfile: Dockerfile
    image: vite-docker:v1
    ports:
      - 9000:9000
    volumes:
      - ./frontend/:/var/www/html/app