apiVersion: v1
kind: Namespace
metadata:
  name: rso-deploy

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productapp-deployment
  namespace: rso-deploy
  labels:
    app: productapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productapp
  template:
    metadata:
      labels:
        app: productapp
        component: backend
    spec:
      containers:
        - name: productapp
          image: zankor/productapp:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 9000
          env:
          - name: BACKEND_SERVER_URL
            value: producthandler-api
---
apiVersion: v1
kind: Service
metadata:
  name: productapp-service
  namespace: rso-deploy
  labels:
    app: producthandler
spec:
  type: ClusterIP
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: productapp
    component: backend
---

